# Generated by Django 4.2.2 on 2024-07-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Cтатус подписки"
            ),
        ),
    ]